# 异常
- 什么是异常？
Java 中的错误⼤致可以分为两类：
⼀类是编译时错误，⼀般是指语法错误。
另⼀类是运⾏时错误。
Java 中有⼀组专⻔⽤来描述各种不同的运⾏时异常，叫做异常类，Java 结合异常类提供了处理错误的机
制。
具体步骤是当程序出现错误时，会创建⼀个包含错误信息的异常类的实例化对象，并⾃动将该对象提交
给系统，由系统转交给能够处理异常的代码进⾏处理。
异常可以分为两类：Error 和 Exception。
Error 是指系统错误，JVM ⽣成，我们编写的程序⽆法处理。
Exception 指程序运⾏期间出现的错误，我们编写的程序可以对其进⾏处理。
- 异常的使⽤
异常的使⽤需要⽤到两个关键字 try 和 catch，并且这两个关键字需要结合起来使⽤，⽤ try 来监听可能
会抛出异常的代码，⼀旦捕获到异常，⽣成异常对象并交给 catch 来处理，基本语法如下所示。
```java
try{
 //可能抛出异常的代码
}catch(Exception e){
 //处理异常
}finally{
  //必须执行的代码
}
```

```java
public class Test {
 public static void main(String[] args) {
 try {
 int num = 10/10;
 }catch (Exception e) {
 // TODO: handle exception
 if(e.getMessage().equals("/ by zero")) {
 System.err.println("分⺟不能为0");
 }
 }finally{
  Syestem.out.println("异常处理");
 }
 }
}
```
- 异常类
Java 将运⾏时出现的错误全部封装成类，并且不是⼀个类，⽽是⼀组类。同时这些类之间是有层级关系
的，由树状结构⼀层层向下分级，处在最顶端的类是 Throwable，是所有异常类的根结点。
Throwable 有两个直接⼦类：Error 和 Exception。
Error 的⼦类包括 VirtualMachineError、AWTError、IOError。
VirtualMachineError 的⼦类有 StackOverflowError、OutOfMemoryError。
Exception 的⼦类包括 IOException 和 RuntimeException。
IOException 的⼦类包括 FileLockInterruptionException、FileNotFoundException、FilerException。
RuntimeException 的⼦类包括 ArithmeticException、ClassNotFoundException、
IllegalArggumentException、ArrayIndexOutOfBoundsException、NullPointerException、
NoSuchMethodException、NumberFormatException。
### 
### **异常**
try-catch-finally

### **异常类**
- Error：系统错误，程序⽆法处理。
- Exception：程序运⾏时出现的错误，程序可以处理。
Error 和 Exception 都是 Throwable 的⼦类，Throwable、Error、Exception 都是存放在 java.lang 包
中。
Error 常⻅的⼦类：VirtualMachineError、AWTError、IOError。
VirtualMachineError 的⼦类：StackOverflowError、OutOfMemoryError，⽤来描述内存溢出等系统
问题。
Exception 常⻅的⼦类：IOException 和 RuntimeException
IOException 存放在 java.io 包中，RuntimeException 存放在 java.lang 包中。
IOException 常⻅的⼦类：FileLockInterruptionException、FileNotFoundException、
FilerException，这些异常通常都是处理通过 IO 流进⾏⽂件传输的时候发⽣的错误。
RuntimeException 常⻅的⼦类：
- ArithmeticException：表示数学运算异常。
- ClassNotFoundException：表类未定义异常。
- IllelArgumentException：表示参数格式错误。
- ArrayIndexOutOfBounds：表示数组下标越界。
- NullPointException：表示空指针异常。
- NoSuchMethodException：表示⽅法未定义异常。
- NumberFormatException：表示将其他数据类型转为数值类型发⽣的类型不匹配异常。

### **throw 和 throws**
throw 和 throws 是 Java 在处理异常时使⽤的两个关键字，都可以⽤来抛出异常，但是使⽤的⽅式和表
示的含义完全不同。
Java 中抛出异常有 3 种⽅式：
1.     try-catch
2.    使⽤ throw 是开发者主动抛出异常，即读到 throw 代码就⼀定抛出异常，基本语法：throw new
        Exception()，是⼀种基于代码的逻辑⽽主动抛出异常的⽅式。
3.    try-catch 和 throw 都是作⽤于具体的逻辑代码，throws 是作⽤于⽅法的，⽤来描述⽅法可能会抛出的异常。

```java
public class Test {
 public static void main(String[] args) {
 int[] array = {1,2,3};
 test(array,2);
 }
 
 public static void test(int[] array,int index) {
 if(index >= 3 || index < 0) {
 try {
 throw new Exception();
 } catch (Exception e) {
 e.printStackTrace();
 }
 }else {
 System.out.println(array[index]);
 }
 }
}
```
如果⽅法 throws 的是 RuntimeException 异常或者其⼦类，外部调⽤时可以不处理，JVM 会处理。
如果⽅法 throws 的是 Exception 异常或者其⼦类，外部调⽤时必须处理，否则报错。
```java
public class Test {
 public static void main(String[] args) throws Exception {
 test("123");
 }
 
 public static void test(String str) throws Exception {
 int num = Integer.parseInt(str);
 }
 }
```

### **异常捕获**
- ⾃动捕获 try-cath
- throw 主动抛出异常
- throws 修饰可能抛出异常的⽅法

### **⾃定义异常**
除了使⽤ Java 提供的异常外，也可以根据需求来⾃定义异常。
```java
public class MyNumberException extends RuntimeException {
 public MyNumberException(String error) {
 super(error);
 }
}
-------------------------------------------------------------------------------------
public class Test {
 public static void main(String[] args){
 Test test = new Test();
 System.out.println(test.add("a"));
 }
 
 public int add(Object object){
 if(object instanceof Integer) {     //判断左边对象是否是右边的类型
 int num = (int)object;
 return ++num;
 }else {
 String error = "传⼊的参数不是整数类型";
 MyNumberException myNumberException = new MyNumberException(error);
 throw myNumberException;
 }
 }
}
```
